server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: price-products
  boot:
    admin:
      client:
        url: http://lochalhost:8099
management:
  endpoints:
    web:
      exposure:
        include: "*"