server:
  port: 8080
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: servicio-products
        uri: lb://servicio-products
        predicates:
        - Path=/product/**
      - id: price-products
        uri: lb://price-products
        predicates:
        - Path=/get-price/**, /get-all-prices
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"