
#Application Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: servicio-products
  
management:
  endpoints:
    web:
      exposure:
        include: "*"